// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-rDPT2jSFP7NZ917e28LQv-lGgMkbfc',
    appId: '1:1007988244157:web:180f9e46891fd5db5481d4',
    messagingSenderId: '1007988244157',
    projectId: 'flutterfirefly-59b0e',
    authDomain: 'flutterfirefly-59b0e.firebaseapp.com',
    storageBucket: 'flutterfirefly-59b0e.firebasestorage.app',
    measurementId: 'G-30FHYH6HNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIdicoRWLr718HoKaxYb59WSKr6IafNk',
    appId: '1:1007988244157:android:4be9c4c253f1e34d5481d4',
    messagingSenderId: '1007988244157',
    projectId: 'flutterfirefly-59b0e',
    storageBucket: 'flutterfirefly-59b0e.firebasestorage.app',
  );
}
